databases:
  - name: keycloak-db
    databaseName: keycloak
    user: keycloak
    plan: free
    region: oregon

services:
  - type: web
    name: keycloak
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL_HOST
        fromDatabase:
          name: keycloak-db
          property: host
      - key: KC_DB_URL_PORT
        fromDatabase:
          name: keycloak-db
          property: port
      - key: KC_DB_URL_DATABASE
        fromDatabase:
          name: keycloak-db
          property: database
      - key: KC_DB_USERNAME
        fromDatabase:
          name: keycloak-db
          property: user
      - key: KC_DB_PASSWORD
        fromDatabase:
          name: keycloak-db
          property: password
      - key: KC_HTTP_ENABLED
        value: "true"
      - key: KC_PROXY_HEADERS
        value: "xforwarded"
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        generateValue: true
      - key: KC_HOSTNAME_STRICT
        value: "false"
